---
- hosts: "{{hostname}}"
  become: yes
  gather_facts: false
  vars:
    - apt_file: /etc/apt/sources.list.d/google-chrome.list
  tasks:
    - name: Add Google Chrome key
      shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - name: Add Google Chrome repo
      copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest="{{apt_file}}" owner=root group=root mode=644
    - name: Update apt cache
      apt: update_cache=yes
    - name: Install Google Chrome
      apt: 
        pkg: google-chrome-stable
        state: latest
    - name: find chrome version
      #shell: google-chrome --version | awk -F' ' '{print $3}'
      shell: echo '120.0.6099.109'
      register: chrome_ver
    - debug:
        var: chrome_ver.stdout
    - name: Download chrome-driver
      get_url:
        url: "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/{{chrome_ver.stdout}}/linux64/chromedriver-linux64.zip"
        dest: /tmp/
        mode: '0755'
    - name: install unzip
      apt:
        name: unzip
        state: latest
    - name: unzip and install chrome-driver
      shell: unzip -o /tmp/chromedriver-linux64.zip  && mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver && chromedriver --version
